
BEGIN TRY
	SET NOCOUNT ON
	SET XACT_ABORT ON

	BEGIN TRANSACTION

	
	BEGIN
	declare @id UNIQUEIDENTIFIER
	SET @id='C587CA3D-41A0-4A73-BE15-1B1BB677E982'

	IF NOT EXISTS (SELECT id FROM [UbiClub].[t_GameSession] 
	WHERE [Id]=@id)
	BEGIN
		INSERT INTO [UbiClub].[t_GameSession] ([Id])
		VALUES (@id);
	END
	
	SET @id='EC1CC1F5-8BE4-43CA-82BF-44D27C9F3430'
	IF NOT EXISTS (SELECT id FROM [UbiClub].[t_GameSession] 
	WHERE [Id]=@id)
	BEGIN
		INSERT INTO [UbiClub].[t_GameSession] ([Id])
		VALUES (@id);
	END

	SET @id='B1784629-7273-4AE8-AA1B-B3A6CBE47646'
	IF NOT EXISTS (SELECT id FROM [UbiClub].[t_GameSession] 
	WHERE [Id]=@id)
	BEGIN
		INSERT INTO [UbiClub].[t_GameSession] ([Id])
		VALUES (@id);
	END
	
	

	COMMIT TRANSACTION
	END
END TRY

BEGIN CATCH
	PRINT ERROR_MESSAGE() 
	ROLLBACK TRANSACTION
	RAISEERROR
END CATCH
